In [1]:
from pathlib import Path

file_path = 'G:\My Drive\Jon BOB Transfer'
upload_path = Path(file_path) / "Uploads"
raw_data_path = Path(file_path) / "raw data"

<>:3: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:3: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\kenny.myers\AppData\Local\Temp\ipykernel_41512\880043530.py:3: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  file_path = 'G:\My Drive\Jon BOB Transfer'

In [2]:
import pandas as pd
import sqlalchemy as sa
from getpass import getpass

# 1. Gather your credentials (mirroring your MySQL Workbench setup)
DB_USER = "kenny.myers"          # Username from Workbench
DB_HOST = "127.0.0.1"   # The Host/IP from Workbench
DB_PORT = "3307"                   # Default MySQL port
DB_NAME = "JonJohnson"              # Database name from your Redtail header

# 2. Securely prompt for password
DB_PASS = getpass("Enter Database Password: ")

# 3. Construct the SQLAlchemy Connection URI
# Format: mysql+pymysql://user:pass@host:port/dbname
connection_uri = f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# 4. Create the engine
engine = sa.create_engine(connection_uri)

print("Engine created successfully. Testing connection...")

Engine created successfully. Testing connection...

In [3]:
# Test query to pull the Household table

# SQL query input

sql_query = """
    SELECT 
        f.id,
        f.name,
        cf.deleted AS primary_member_deleted,
        f.deleted AS family_deleted,
        f.created_at
    FROM contact_families AS f
    LEFT JOIN contact_family_members AS cf 
        ON cf.family_id = f.id 
        -- Force a 1:1 match by specifying exactly which member you want
        AND cf.hoh = 1;
"""
try:
    with engine.connect() as conn:
        df_family = pd.read_sql(sql_query, conn)
    print("Connection successful! Previewing data:")
    display(df_family.head())
except Exception as e:
    print(f"Connection failed. Error: {e}")

Connection successful! Previewing data:

,id,name,primary_member_deleted,family_deleted,created_at
0,1,"Hanson,K",1,1,2019-09-11 18:14:18
1,2,Chocholousek Family,0,0,2019-09-20 15:34:40
2,3,Allardyce Family,0,0,2019-09-23 19:25:25
3,4,Anderson Family,0,0,2019-09-23 19:26:21
4,5,Asheim Family,0,0,2019-09-23 19:28:20

In [4]:
# Query contacts table for family validations

contacts_query = """
    SELECT c.id AS contact_id,
	c.first_name,
    c.last_name,
    c.created_at,
    c.company_name,
    c.client_since,
    
    c.deleted
FROM contacts AS c;
"""
try:
    with engine.connect() as conn:
        df_contacts = pd.read_sql(contacts_query, conn)
    print("Connection successful! Previewing data:")
    display(df_contacts.head())
except Exception as e:
    print(f"Connection failed. Error: {e}")

Connection successful! Previewing data:

,contact_id,first_name,last_name,created_at,company_name,client_since,deleted
0,1,NaN,NaN,2019-09-09 19:36:30,US Land Professionals,None,0
1,2,Karen,Goeringer,2019-09-09 19:36:30,NaN,None,0
2,3,Jon,Johnson,2019-09-09 19:47:51,NaN,None,1
3,4,Donnell,Wilson,2019-09-09 21:17:55,NaN,None,1
4,5,Karen,Hanson,2019-09-09 21:19:50,NaN,None,0

In [5]:
# Query contacts table for family validations

contacts_query = """
    SELECT id,
        family_id,
        contact_id
FROM contact_family_members AS cf;
"""
try:
    with engine.connect() as conn:
        df_family_members = pd.read_sql(contacts_query, conn)
    print("Connection successful! Previewing data:")
    display(df_family_members.head())
except Exception as e:
    print(f"Connection failed. Error: {e}")

Connection successful! Previewing data:

     id  family_id  contact_id
0   652        378           2
1   843        560           2
2   779        499           4
3     1          1           5
4  1059        771           5

In [6]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(df_family):
    # Filter rows based on column: 'primary_member_deleted'
    df_family = df_family[df_family['primary_member_deleted'] == 0]
    # Drop duplicate rows in column: 'name'
    df_family = df_family.drop_duplicates(subset=['name'])
    return df_family

df_family_clean = clean_data(df_family.copy())
df_family_clean.head()

,id,name,primary_member_deleted,family_deleted,created_at
1,2,Chocholousek Family,0,0,2019-09-20 15:34:40
2,3,Allardyce Family,0,0,2019-09-23 19:25:25
3,4,Anderson Family,0,0,2019-09-23 19:26:21
4,5,Asheim Family,0,0,2019-09-23 19:28:20
5,6,Austin Family,0,0,2019-09-23 19:29:24

In [7]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(df_contacts):
    # Change column type to datetime64[ns] for column: 'client_since'
    df_contacts = df_contacts.astype({'client_since': 'datetime64[ns]'})
    # Filter rows based on column: 'deleted'
    df_contacts = df_contacts[df_contacts['deleted'] == 0]
    return df_contacts

df_contacts_clean = clean_data(df_contacts.copy())
df_contacts_clean.head()

,contact_id,first_name,last_name,created_at,company_name,client_since,deleted
0,1,NaN,NaN,2019-09-09 19:36:30,US Land Professionals,NaT,0
1,2,Karen,Goeringer,2019-09-09 19:36:30,NaN,NaT,0
4,5,Karen,Hanson,2019-09-09 21:19:50,NaN,NaT,0
5,6,NaN,NaN,2019-09-09 21:28:48,Diamond Family Medicine,NaT,0
6,7,Paula,Berg,2019-09-09 21:28:48,NaN,NaT,0

In [8]:
# Moves buisness HHs out of the contacts table and into a new table for business HHs

# 1. Create a boolean mask to identify which rows have a company name
# Use notna() to catch proper nulls, and explicitly check for empty strings
is_business = df_contacts_clean['company_name'].notna() & (df_contacts_clean['company_name'].str.strip() != '')

# 2. Extract those specific rows into a brand new DataFrame
# The .copy() is critical to prevent SettingWithCopyWarnings downstream
df_business_hh = df_contacts_clean[is_business].copy()

# 3. Filter the original DataFrame to keep ONLY the individuals
# The ~ operator inverses the boolean mask (keep where it is NOT a business)
df_contacts_clean = df_contacts_clean[~is_business].copy()

# 4. Optional Validation: Ensure no records were lost in the split
original_count = len(df_contacts_clean) + len(df_business_hh)
print(f"Total Business/HH records extracted: {len(df_business_hh)}")
print(f"Total Individual records remaining: {len(df_contacts_clean)}")

Total Business/HH records extracted: 96
Total Individual records remaining: 1828

In [18]:
import pandas as pd

# Assume df_contacts and df_family_members are already loaded in your notebook

# 1. Identify which contacts are already linked to a family
# The isin() function checks if the contact's 'id' exists anywhere in the family members 'contact_id' column
has_family_mask = df_contacts_clean['contact_id'].isin(df_family_members['contact_id'])

# 2. Extract the orphaned contacts into a new DataFrame
# The ~ operator inverts the mask (keep those who do NOT have a family match)
# .copy() prevents SettingWithCopy warnings if you modify this dataframe later
df_unhoused_contacts = df_contacts_clean[~has_family_mask].copy()

# 3. Validation output for your notebook
print(f"Total starting contacts: {len(df_contacts)}")
print(f"Contacts successfully mapped to a Household: {has_family_mask.sum()}")
print(f"Orphaned contacts (df_unhoused_contacts): {len(df_unhoused_contacts)}")

Total starting contacts: 2047
Contacts successfully mapped to a Household: 1229
Orphaned contacts (df_unhoused_contacts): 599

In [19]:
# Define your M&A specific prefix (e.g., Target Firm Initials _ Source CRM _ Date)
# Let's say JH = Jackson Holdings (the target firm)
ma_prefix = "JJ_RT_202611"

# 1. Update the Anchor Object (Contacts)
df_contacts_clean['Legacy_Contact_ID__c'] = f"{ma_prefix}_CNT_" + df_contacts_clean['contact_id'].astype(str)

# 2. Update the Child Objects (Emails, Phones, ACRs) so they can still find their parent
# Notice we are prefixing the FOREIGN KEY (contact_id) exactly the same way
#df_emails['Legacy_Contact_ID__c'] = f"{ma_prefix}_CNT_" + df_emails['contact_id'].astype(str)
#df_family_members['Legacy_Contact_ID__c'] = f"{ma_prefix}_CNT_" + df_family_members['contact_id'].astype(str)

# 3. Do the same for Families (Households)
df_family_clean['Legacy_Family_ID__c'] = f"{ma_prefix}_HH_" + df_family_clean['id'].astype(str)
df_family_members['Legacy_Family_ID__c'] = f"{ma_prefix}_HH_" + df_family_members['family_id'].astype(str)

In [20]:
# import pandas as pd

# # Assume df_contacts and df_family_members are already loaded in your notebook

# # 1. Identify which contacts are already linked to a family
# # The isin() function checks if the contact's 'id' exists anywhere in the family members 'contact_id' column
# has_family_mask = df_contacts_clean['contact_id'].isin(df_family_members['contact_id'])

# # 2. Extract the orphaned contacts into a new DataFrame
# # The ~ operator inverts the mask (keep those who do NOT have a family match)
# # .copy() prevents SettingWithCopy warnings if you modify this dataframe later
# df_unhoused_contacts = df_contacts_clean[~has_family_mask].copy()

# # 3. Define the M&A prefix (update this to match your firm's naming convention for this deal)
# ma_prefix = "JJ_RT_202611"

# # 4. Generate synthetic Household External IDs and Names for the orphaned contacts
# # We use "SOLO_" plus the contact ID to guarantee it never collides with an actual Redtail Family ID
# df_unhoused_contacts['Legacy_Family_ID__c'] = f"{ma_prefix}_HH_SOLO_" + df_unhoused_contacts['contact_id'].astype(str)

# # Handle potential null last names gracefully, as legacy CRMs sometimes have blank last names
# df_unhoused_contacts['Household_Name'] = df_unhoused_contacts['last_name'].fillna('Unknown') + ' Household'

# # 5. Create the actual DataFrame for these new Household records
# # This isolates just the columns needed for the Account (Household) upsert
# df_synthetic_households = df_unhoused_contacts[['Legacy_Family_ID__c', 'Household_Name']].copy()

# # 6. Validation output for your notebook
# print(f"Total starting contacts: {len(df_contacts)}")
# print(f"Contacts successfully mapped to a Household: {has_family_mask.sum()}")
# print(f"Orphaned contacts (df_unhoused_contacts): {len(df_unhoused_contacts)}")
# print(f"Successfully generated {len(df_synthetic_households)} synthetic households.")

In [24]:
import pandas as pd

# --- Defensive reset for Jupyter cell re-runs ---
if 'Generated_Name' in df_family_clean.columns:
    df_family_clean = df_family_clean.drop(columns=['Generated_Name'])
if 'family_id' in df_family_clean.columns:
    df_family_clean = df_family_clean.drop(columns=['family_id'])

# --- 1. REBUILD STANDARD FAMILY NAMES ---
# Coerce foreign keys to nullable integers to guarantee the inner merge connects
df_family_details = df_family_members.astype({'contact_id': 'Int64'}).merge(
    df_contacts_clean[['contact_id', 'first_name', 'last_name']].astype({'contact_id': 'Int64'}), 
    on='contact_id', 
    how='inner'
)

if df_family_details.empty:
    print("WARNING: df_family_details is empty. No linked contacts were found in the junction table.")
    df_family_clean['Generated_Name'] = 'Unknown Household'
else:
    def build_hh_name(group):
        # Sort by contact_id so the oldest/primary record anchors the name
        group = group.sort_values('contact_id')
        
        last_names = group['last_name'].fillna('Unknown').tolist()
        first_names = group['first_name'].fillna('').tolist()
        
        primary_last = last_names[0]
        
        if len(first_names) == 1:
            return f"{primary_last}, {first_names[0]}".strip(', ')
        else:
            # Grabs the first two contacts (Primary and typically Spouse)
            return f"{primary_last}, {first_names[0]} and {first_names[1]}".strip(', ')

    # Apply the logic and map it back to the household dataframe
    df_generated_names = df_family_details.groupby('family_id').apply(build_hh_name).reset_index(name='Generated_Name')
    df_family_clean = df_family_clean.merge(df_generated_names, left_on='id', right_on='family_id', how='left')
    
    # Catch any standard families that lacked entries in the junction table
    df_family_clean['Generated_Name'] = df_family_clean['Generated_Name'].fillna('Unknown Household')

# --- 2. MAP BUSINESS ENTITIES ---
df_export_businesses = pd.DataFrame({
    'Name': df_business_hh['company_name'], 
    'FinServ__SourceSystemId__c': df_business_hh['Legacy_Account_ID__c']
})

# --- 3. BUILD SYNTHETIC UNHOUSED CONTACTS ---
last_name_clean = df_unhoused_contacts['last_name'].fillna('Unknown')
first_name_clean = df_unhoused_contacts['first_name'].fillna('')

df_export_unhoused = pd.DataFrame({
    'Name': (last_name_clean + ', ' + first_name_clean).str.rstrip(', '),
    'FinServ__SourceSystemId__c': df_unhoused_contacts['Legacy_Contact_ID__c']
})

# --- 4. STACK AND VALIDATE FINAL EXPORT ---
df_export = pd.concat([df_export_families, df_export_businesses, df_export_unhoused], ignore_index=True)

# Drop nulls
df_export.dropna(subset=['FinServ__SourceSystemId__c', 'Name'], inplace=True)
df_export.drop_duplicates(subset=['FinServ__SourceSystemId__c'], inplace=True)

print(f"Total Accounts ready for export: {len(df_export)}")
print(df_export.sample(5))

Total Accounts ready for export: 1405
                                Name FinServ__SourceSystemId__c
597       Rabell, Juanita and Hansel        JJ_RT_202611_HH_975
177                Furniture, Trends        JJ_RT_202611_HH_276
792   Hagen Glass Windows and Siding      JH_RT_202608_BUS_2262
1283                 Richters, Rocco      JJ_RT_202611_CNT_1882
554                   Hammock, Dayle        JJ_RT_202611_HH_920

In [25]:
# Assuming df_businesses was created via your boolean mask
# e.g., df_businesses = df_contacts_clean[df_contacts_clean['is_business_mask']].copy()

# Define the M&A prefix consistently
ma_prefix = "JH_RT_202608"

# 1. Generate the Business Account External ID
# Using _BUS_ ensures these don't collide with _HH_ or _CNT_ records
df_business_hh['Legacy_Account_ID__c'] = f"{ma_prefix}_BUS_" + df_business_hh['contact_id'].astype(str)

# 2. Map standard fields for the Business Account upsert
# You will likely map the company_name to the Salesforce Account Name
df_business_hh['Account_Name'] = df_business_hh['company_name']

# 3. Validation
print(f"Total Business Accounts processed: {len(df_business_hh)}")
print("Sample External IDs:")
print(df_business_hh[['contact_id', 'Account_Name', 'Legacy_Account_ID__c']].head())

Total Business Accounts processed: 96
Sample External IDs:
     contact_id             Account_Name   Legacy_Account_ID__c
0             1    US Land Professionals     JH_RT_202608_BUS_1
5             6  Diamond Family Medicine     JH_RT_202608_BUS_6
698         699   Jo Momma Says Business   JH_RT_202608_BUS_699
843        1146                Breadroot  JH_RT_202608_BUS_1146
859        1162       Kauk's Meat Market  JH_RT_202608_BUS_1162

In [27]:
import pandas as pd

# 1. Map the standard Redtail families
df_export_families = pd.DataFrame({
    'Name': df_family_clean['name'],
    'FinServ__SourceSystemId__c': df_family_clean['Legacy_Family_ID__c']
})

# 2. Map the business entities
df_export_businesses = pd.DataFrame({
    'Name': df_business_hh['company_name'], 
    'FinServ__SourceSystemId__c': df_business_hh['Legacy_Account_ID__c']
})

# 3. Map the orphaned contacts to synthetic households
# Reformatted to strictly [Last Name], [First Name] for single individuals
last_name_clean = df_unhoused_contacts['last_name'].fillna('Unknown')
first_name_clean = df_unhoused_contacts['first_name'].fillna('')

df_export_unhoused = pd.DataFrame({
    'Name': (last_name_clean + ', ' + first_name_clean).str.rstrip(', '),
    'FinServ__SourceSystemId__c': df_unhoused_contacts['Legacy_Contact_ID__c']
})

# 4. Stack them vertically into the final export payload
df_export = pd.concat(
    [df_export_families, df_export_businesses, df_export_unhoused], 
    ignore_index=True
)

# Optional: drop any accidental duplicates or NaNs before export
df_export.dropna(subset=['FinServ__SourceSystemId__c'], inplace=True)
df_export.drop_duplicates(subset=['FinServ__SourceSystemId__c'], inplace=True)

# Validation
print(f"Total Accounts ready for export: {len(df_export)}")
print(df_export.sample(5))

Total Accounts ready for export: 1405
                     Name FinServ__SourceSystemId__c
1183          Doom, Mindy      JJ_RT_202611_CNT_1742
454   Lance Deles Dernier        JJ_RT_202611_HH_804
385       Darci McManigal        JJ_RT_202611_HH_732
1376  Three Stars, Shayda      JJ_RT_202611_CNT_2261
65        Keffeler Family         JJ_RT_202611_HH_81

In [28]:
# Add the required Salesforce fields for the Household upsert

df_export = df_export.assign(
    Lead_Advisor_FA_Rep__c='0034X00003DlUUXQA3',
    RecordTypeId='0125e000001BtltAAC',
    Exclude_from_Addepar_Sync__c=True
)

In [29]:
from pathlib import Path

# Assuming upload_path is defined earlier as a string (e.g., 'C:/data/exports')
# 1. Cast the base string to a Path object first
# 2. Then use the / operator to append the file name
export_file = Path(upload_path) / '01_transform_households.csv'

# --- 1. Export the CSV Payload for Data Loader ---
df_export.to_csv(export_file, index=False)

# --- 2. Export the Audit Trail Excel Workbook ---
# Apply the same logic for your raw_data_path
excel_file = Path(raw_data_path) / '01_transform_households_raw.xlsx'
# with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
# ...

In [30]:
from os import path

import pandas as pd
from openpyxl.styles import PatternFill, Font, Border, Side, Alignment
from openpyxl.utils import get_column_letter

# Define your output paths (you can parameterize these with your M&A prefix if needed)
#upload_path = 'salesforce_account_export.csv'
#raw_data_path = 'redtail_migration_raw_data.xlsx'

# --- 1. Export the CSV Payload for Data Loader ---
#df_export.to_csv(path(upload_path / '01_transform_households.csv'), index=False)


# --- 2. Export the Audit Trail Excel Workbook ---
dfs = {
    'Export Payload': df_export,
    'Businesses': df_business_hh,
    'Family Raw': df_family,
    'Family Clean': df_family_clean,
    'Contacts Raw': df_contacts,
    'Contacts Clean': df_contacts_clean,
    'Family Members': df_family_members,
    'Unhoused Contacts': df_unhoused_contacts
}

with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
    
    # Pre-define Excel styling properties
    header_fill = PatternFill(start_color="2E3440", end_color="2E3440", fill_type="solid")
    header_font = Font(color="ECEFF4", bold=True)
    border_bottom = Border(bottom=Side(style='thin', color='D8DEE9'))
    row_fill_alt = PatternFill(start_color="F9F9FB", end_color="F9F9FB", fill_type="solid")
    
    for sheet_name, df in dfs.items():
        # Make a copy to avoid SettingWithCopy warnings during formatting
        df_out = df.copy()
        
        # Defensive check: Drop timezone info from any datetime columns to prevent Excel export errors
        dt_cols = df_out.select_dtypes(include=['datetime64', 'datetimetz']).columns
        for col in dt_cols:
            df_out[col] = df_out[col].dt.tz_localize(None)
            
        # Write the dataframe to its designated sheet
        df_out.to_excel(writer, sheet_name=sheet_name, index=False)
        worksheet = writer.sheets[sheet_name]
        
        # Apply formatting column by column
        for col_num, col_name in enumerate(df_out.columns.values):
            col_letter = get_column_letter(col_num + 1)
            
            # Header styling
            header_cell = worksheet[f"{col_letter}1"]
            header_cell.fill = header_fill
            header_cell.font = header_font
            header_cell.alignment = Alignment(horizontal='center', vertical='center')
            header_cell.border = border_bottom
            
            # Auto-adjust column width (capped at 40 width)
            if not df_out[col_name].empty:
                # 1. Use .str.len() instead of .map(len) for safe handling of nulls/ExtensionArrays
                max_data_len = df_out[col_name].astype(str).str.len().max()
                
                # 2. If the column is completely null, max_data_len becomes NaN. Catch it here.
                if pd.isna(max_data_len):
                    max_data_len = 0
                    
                # 3. Compare data length to column header length
                max_length = max(int(max_data_len), len(str(col_name)))
            else:
                max_length = len(str(col_name))
            
            worksheet.column_dimensions[col_letter].width = min(max_length + 2, 40)
            
        # Freeze the top row for auditing
        worksheet.freeze_panes = "A2"
        
        # Apply subtle zebra striping
        for row_num in range(2, worksheet.max_row + 1):
            if row_num % 2 == 0:
                for col_num in range(1, worksheet.max_column + 1):
                    worksheet.cell(row=row_num, column=col_num).fill = row_fill_alt

#print(f"Pipeline checkpoint saved successfully:\n - CSV: {csv_file}\n - Excel Audit: {excel_file}")